# Generated by Django 5.1.6 on 2025-02-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medication',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcare_tool.doctor'),
        ),
    ]
