# Generated by Django 5.1.7 on 2025-04-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_tool', '0002_patient_medication_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcare_tool.bed'),
        ),
    ]
